<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wswordpressgrab"
 *
 * Auto generated by Extension Builder 2014-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Wordpress Grabber',
	'description' => 'Get post from wordpress blog via external connection to database',
	'category' => 'plugin',
	'author' => 'Nikolay Orlenko',
	'author_email' => 'info@web-spectr.com',
	'author_company' => 'Web.Spectr http://web-spectr.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.6.4',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);